# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [ "--fix", "src", "tests" ]
      - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
      # Note: since we run mypy on the tests/ folder also we need to add pytest as
      #       additional dependency
        additional_dependencies:
          - types-colorama==0.4.15.20240311
          - types-docutils==0.20.0.20240317
          - types-click==7.1.8
          - mypy==1.9.0
          - pytest==8.1.1
        args: []
        pass_filenames: false
        entry: ./pre-commit-helpers/run_mypy.sh
-   repo: local
    hooks:
      - id: coverage
        name: coverage
        language: system
        entry: bash -c 'coverage run -m pytest tests && coverage report -m'
        always_run: true
        pass_filenames: false
